apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.path }}
  storageClassName: {{ .Values.pv.storageClassName }}